### PR TITLE
cide package: add a way to inject version data

### PR DESCRIPTION
**Pull request by zimbatm**
.packager/version can contain either a git sha, short sha or the automated
build version.

/cc @Nicowcow

### CODE REVIEW

**Comment by Nicowcow** [comment]
nice. would it be helpful to have it on the command line as well? that would mean allow overwriting even more of the config.

**Comment by zimbatm** [comment]
It's already the case if it's set to "auto", you can set the `--build-id=something`. I would be tempted to let it as is and add the option later if necessary ?

**Comment by Nicowcow** [comment]
I could see some use cases (though not that many) where you'd want the version to be different from the build-id, but there are other ways to achieve this. I'm definitely good with leaving it as it is now!

**Comment by zimbatm** [comment]
Yeah. There are a lot of things I want to rethink eventually. I can see how users might want to produce different kinds of packages built with different docker images. Right now it's quite tied to how our system works.

**Pull request merged**
